#!/bin/bash
#
#  /etc/rc.d/init.d/av_server
#  chkconfig: 2345 80 30
#  Description: start_socket_server_to_serve_av_checks_by_path
#  
### BEGIN INIT INFO
# Provides: av_server
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop av_server
# Description: Postfix is a Mail Transport Agent, which is the program that 
#              moves mail from one machine to another.
### END INIT INFO

# Source function library.
. /etc/init.d/functions
PROGRAM=/usr/local/bin/dkav

start() {
	echo -n "Starting av_server: "
	daemon ${PROGRAM}
	touch /var/lock/subsys/av_server
	return $?
}	

stop() {
	echo -n "Shutting down av_server: "
	killall dkav
	rm -f /var/lock/subsys/av_server
	return 0
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
    	stop
	start
	;;
    *)
	echo "Usage: av_server {start|stop|restart}"
	exit 1
	;;
esac
exit $?
